# Generated by Django 4.2.7 on 2023-12-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaRoma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pizza', models.CharField(max_length=100)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
