# Generated by Django 4.2.7 on 2023-12-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PizzaRoma', '0004_alter_pizza_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='cantidad_vendida',
            field=models.IntegerField(default=0),
        ),
    ]
